Parsing of  data from the M3 Sonar API to ROS2 PointCloud2 for usage in autonomous systems.
vortexntnu/vortex-m3-sonar-driver pull request #7
Opened 2024-01-09 14:50 UTC by iTroned

Closes #1 

Created a client connecting to the API with at a socket, reading the data as it arrives. Another thread requests this data at a chosen interval, parses the data to a point cloud and publishes it on a chosen topic.

2024-01-10 17:41 UTC, EirikKolas requested changes
Great work. Only a couple minor code quality things I'm pedantic about

2024-01-10 17:41 UTC, EirikKolas commented on src/imb/M3Publisher.cpp
> +            if(packet_ready_){
replace with `if (!packet_ready_) return;` to avoid nesting

2024-01-10 17:41 UTC, EirikKolas commented on src/imb/imbFormat.cpp
remove commented out code

2024-01-10 17:41 UTC, EirikKolas commented on src/imb/M3Publisher.cpp
> +                }
Not a fan of the math being calculated in the ros node class. Could this be moved to the `imb::DataBody` class perhaps?

2024-01-10 17:41 UTC, EirikKolas commented on src/utils/RingBuffer.hpp
Delete the ringbuffer if it isn't used

2024-01-10 17:41 UTC, EirikKolas commented on test/ImbFormatTest.cpp
> +}
Either finish the test or remove it :)

2024-01-12 08:31 UTC, alekskl01 commented on src/utils/netUtils.cpp
> +        // return;
comment back in or remove

2024-01-12 08:31 UTC, alekskl01 commented on test/M3SonarTest.cpp
remove commented out code

2024-01-22 13:00 UTC, EirikKolas approved these changes

2024-01-22 13:01 UTC, merged